title: Charis Chrisna's Portfolio # your name (or website title) here
#logo: "/images/charis.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A hobbyist data scientist, using this site as a portfolio of my built projects and upcoming showcases.
  <br><br>
  Reach me out at:
  <br>
  charischrisna3@gmail.com
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
