title: Charis Chrisna # your name (or website title) here
logo: "/images/charis.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  An Ocean Engineering student from Sepuluh Nopember Institute of Technology, Surabaya. Goal-oriented and result-driven individual who drives beyond the limit to achieve the ideal desired outcome. Believes that concepting and executing ideas are a fresh challenge, determining the most optimal operational method in the process of achieving all objectives.
  <br><br>
  Currently programming as a hobby, and will post various projects built in this portfolio of a website. Aside from Data Science, some of my projects are also in the field of Computer Science.
  <br><br>
  Reach me out at:
  <br>
  charischrisna3@gmail.com
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
