title: Charis Chrisna's Portfolio
#logo: "/images/charis.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi! My name is Charis Chrisna. I'm a hobbyist data scientist, using this site as a portfolio of my built projects and upcoming showcases.
  <br><br>
  Reach me out at:
  <br>
  charischrisna3@gmail.com
  
theme: jekyll-theme-dinky
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
